### PR TITLE
add OSName to the versionSet table for use in mcwrapper and beyond

### PR DESCRIPTION
**Pull request by T-Britton**

### CODE REVIEW

**Comment by aaust** [comment]
Do you wan to fill this entry with the crawler?

**Comment by T-Britton** [comment]
we will.  When we have a hook embedded somewhere for the crawler to latch on to.  This will have to come in a second  PR.

I would think in the version set xml....somewhere...maybe.  but that may not be too trivial as a vs may have more than one builds on different OSs


Thomas Britton
Staff Scientist in Scientific Computing
Jefferson Lab
x7624
________________________________
From: Alexander Austregesilo ***@***.***>
Sent: Tuesday, November 19, 2024 1:40 PM
To: JeffersonLab/build_scripts ***@***.***>
Cc: Thomas Britton ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [JeffersonLab/build_scripts] add OSName to the versionSet table for use in mcwrapper and beyond (PR #272)


Do you wan to fill this entry with the crawler?

**Comment by aaust** [comment]
Hm, the crawler could look at the group disk and save a bitmap with an entry for each os. So the integer value works.

**Comment by T-Britton** [comment]
integer value? Oh, no that is a referential ID internal to the DB

**Pull request merged**
