### PR TITLE
Add a custom gcc compiler on the farm and ifarm.

### PR DESCRIPTION
**Pull request by markito3**
The test is only done on whether the node name looks like a farm or ifarm node.

### CODE REVIEW

**Comment by markito3** [comment]
@sdobbs should probably take a look and merge if he likes.

**Comment by sdobbs** [comment]
I like the idea, but instead of tieing the configuration to certain nodes, maybe it would be better to execute the command if we are on a RHEL6/CentOS6 machine, for more generality?

In either case, I'd like to wait to get confirmation from Sandy about the non-interactive nodes..

**Comment by markito3** [comment]
On 06/02/2016 11:44 AM, Sean Dobbs wrote:
>
> I like the idea, but instead of tieing the configuration to certain 
> nodes, maybe it would be better to execute the command if we are on a 
> RHEL6/CentOS6 machine, for more generality?
>
Currently, it does not work on RHEL6 (see jlabl3). And if local folks 
find a non-farm CentOS6 machine at JLab (not something I have heard of), 
it is not likely to work there either. This is a highly JLab-specific 
thing. The thing that might break testing on the node name is if the 
farm nodes become a mix of nodes where some have the module installed 
and some don't, but it is hard to anticipate what the might look like.
>
> In either case, I'd like to wait to get confirmation from Sandy about 
> the non-interactive nodes..
>
If the non-interactive nodes do not behave like the interactive ones, 
that is a SciComp configuration bug. The ostensible purpose of the 
ifarms is to provide a farm-like environment for setting up and testing 
farm jobs.

**Comment by sdobbs** [comment]
OK, sounds good to me.

**Pull request merged**
